### PR TITLE
Support for multiple crop and fill background

### PR DESCRIPTION
**Pull request by erikogabrielsson**
Suggestion for implementing multiple crops from the same image, giving better performance as only one decompress is needed. Also implementation of a callback function that can fill the background (with a gray color) if the crop parameters extends the original image. #44

### CODE REVIEW

**Comment by lilohuang** [comment]
Thanks for your contribution. I will review and resolve merge conflicts this weekend. I forgot to mention that currently PyTurboJPEG still need to support Python 2 interpreter even Python 2 is EOL. Therefore, I will slightly change your code change to make it work with Python 2.

**Comment by lilohuang** [comment]
Hi @erikogabrielsson,

Thanks for your hard work. I gave a try with your code changes, and slightly changed syntax to compatible with Python 2 (see https://github.com/lilohuang/PyTurboJPEG/pull/48/files for details). 

I have a few questions on this work before I do the real merge.
1. Should I add a default value to background_luminance? Your code comment said Default to full, resulting in white background. I don't know where is the default value.
2. I tried to play with the crop_multiple, it does work perfectly with multiple crop regions (crop_parameters), but I don't know how to specify background_luminance value correctly to get **while** or **black** background, I only can see like gray background if crop region is out of image region, I tested it with TurboJPEG 2.1.1 (64bit) on Windows 10.

Could you share a demo code to verify those features? Please take your time. 

Best,
Lilo

**Comment by erikogabrielsson** [comment]
Hi @lilohuang 
To set a default value for background luminance is a bit tricky. What the callback functions does it change the (quantified ) DC DCT coefficients. Depending on the quantitation table (for the luminance channel) this will result in different intensities. The range for the non-quantified coefficients are -1024 - 1023. So to get a white/black image the luminance DC coefficient (after multiplication with the quantification factor) should be higher/lower than 1023/-1024. For a file with (DC) quantification factor of 2, If the DC quantification factor is 2, inserting 512/-512 produces a a white/black image. If the factor is 6 -> 171/-171. The value can be higher, but values higher than 8024 will overflow and flipping white to black (and vice versa). So without knowing the quantification table, one can not set a default value. 

I will make a simple parser that gets the dc quantification coefficient from the jpeg header. It would be nice if the input background luminance parameter was mapped 0-255 (black to white).

**Comment by lilohuang** [comment]
Hi @erikogabrielsson ,

OK, let me merge your code change first, and I will update documentation once you can provide a simple parser to simplify the background luminance value range (e.g. 0-255, or 0.0~1.0).

Thanks,
Lilo

**Pull request merged**
