### PR TITLE
merge new features

### PR DESCRIPTION
**Pull request by lilohuang**

### CODE REVIEW

**Comment by el3ment** [comment]
@austeeen - it is surprising that performing a crop and decoding isn't all that much faster than just decoding (performance boost of about 30%. For example, cropping an image x=0, y=0, w=1, h=1 takes nearly the same amount of time as cropping 500x500. I've seen ImageDecoerCrop from Nvidia's DALI 2x or 3x the crop+decode time over the full frame decode time. I'm looking into it, but I'm wondering if you have seen this. Could this be an issue with library compilation/version?

`jpeg = TurboJPEG()
with tqdm(range(N), ncols=80, position=0, smoothing=0, desc='TurboJPEG') as tqdm_instance:
    for i in tqdm_instance:
        with open(jpeg_filenames[0], 'rb') as fp:
            jpeg.decode(fp.read())


with tqdm(range(N), ncols=80, position=0, smoothing=0, desc='TurboJPEG (Cropped)') as tqdm_instance:
    for i in tqdm_instance:
        with open(jpeg_filenames[0], 'rb') as fp:
            jpeg.crop(fp.read(), x=0, y=0, w=1, h=1)`

**Comment by lilohuang** [comment]
I believe the DALI is not using the TurboJPEG API. They calls the very low-level libjpeg-turbo API directly with skip some scanlines.

**Comment by el3ment** [comment]
ah -- yes, looks like you are correct. It's too bad that they don't do similar logic in `turbojpeg.c` https://github.com/NVIDIA/DALI/blob/master/dali/image/jpeg_mem.cc#L184

**Comment by lilohuang** [comment]
I believe the libjpeg-turbo author clearly understood the partial decoding benefit on TurboJPEG API, it's just not implemented yet. I will add the native partial decoding once it's available.

https://github.com/libjpeg-turbo/libjpeg-turbo/issues/313#issuecomment-457242676

**Pull request merged**
